name: termixd

services:
  termixd:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: termixd:latest
    container_name: termixd
    restart: unless-stopped
    ports:
      - "8083:8080"
    volumes:
      - ./data-dev:/app/data
    environment:
      PORT: "8080"
      GUACD_HOST: "termixd-guacd"
    depends_on:
      - termixd-guacd

  termixd-guacd:
    image: guacamole/guacd:1.6.0
    container_name: termixd-guacd
    restart: unless-stopped
    ports:
      - "4823:4822"

networks:
  default:
    external: true
    name: nginx-proxy
